#!/bin/bash

source ~/.bash_profile
deploy_path="../$1"
if [ ! -d "$deploy_path/$2" ]
then
        mkdir -p $deploy_path
        cd $deploy_path
        project_path="git@gitlab.szkedun.cn:"$1/$2".git"
        echo "ready to clone "$project_path
        git clone $project_path
        cd $2
    git pull
    git checkout -B now $3
else
        cd $deploy_path/$2
        echo "ready to checkout "$3
    git pull
        git checkout -B now $3
fi
echo "开始使用maven构建项目"
mvn clean install -Dmaven.test.skip=true
mkdir -p target/docker
cp dockerfile-staging/Dockerfile target/docker/
cp target/$2.jar target/docker/
cd target/docker
echo "停止旧版本容器"$2
docker stop $2
echo "删除旧版本容器"$2
docker rm $2
echo "删除镜像"$2
docker rmi $2
echo "开始构建容器"$2
docker build -t $2 .
echo "容器"$2"构建完成，启动容器..."
if [ ! -n "$5" ] 
then
        echo "exec logs"
        docker run -d -p $4:$4 -v /home/logs/$1/$2:/home/logs/ -v /etc/localtime:/etc/localtime:ro --privileged --name $2 $2
else
        echo "schedule - $5"
        docker run -d -p $4:$4 -p $5:$5 -v /home/logs/$1/$2/:/home/gitlab-runner/logs/$2/ -v /etc/localtime:/etc/localtime:ro --privileged --name $2 $2
fi
echo "部署成功!!!"
